// Inlines the woff2 files as data URIs into src/fonts.css.
//
//   node tools/embed-font.mjs
//
// Why inline: a url() in CSS resolves differently in the dev server, in the
// built bundle (base './'), and behind Tauri's asset protocol. The font is
// ~16KB total, so sidestepping all three cases is worth the base64 overhead.
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

const FACES = [
  { file: 'silkscreen-400.woff2', weight: 400 },
  { file: 'silkscreen-700.woff2', weight: 700 },
]

const blocks = FACES.map(({ file, weight }) => {
  const b64 = readFileSync(join(ROOT, 'public', 'fonts', file)).toString('base64')
  return `@font-face {
  font-family: 'Silkscreen';
  font-style: normal;
  font-weight: ${weight};
  font-display: block;
  src: url(data:font/woff2;charset=utf-8;base64,${b64}) format('woff2');
}`
})

const css = `/* GENERATED by tools/embed-font.mjs — do not edit by hand.
 *
 * Silkscreen by Jason Kottke, SIL Open Font License 1.1.
 * https://fonts.google.com/specimen/Silkscreen
 * The OFL permits bundling in an application; see art/OFL.txt.
 */

${blocks.join('\n\n')}
`

writeFileSync(join(ROOT, 'src', 'fonts.css'), css)
console.log(`src/fonts.css written (${(css.length / 1024).toFixed(1)} KB)`)
